// Code generated by protoc-gen-go. DO NOT EDIT.
// This is a stub file. Run `make gen-proto` to regenerate.

package pb

import (
	"google.golang.org/protobuf/types/known/timestamppb"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

// ─── Common messages ────────────────────────────────────────────────────────

// User message from common.proto
type User struct {
	Id        string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username  *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password  *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Email     *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	RoleId    *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=role_id,proto3" json:"role_id,omitempty"`
	Token     *wrapperspb.StringValue `protobuf:"bytes,6,opt,name=token,proto3" json:"token,omitempty"`
	CreatedAt *timestamppb.Timestamp  `protobuf:"bytes,7,opt,name=created_at,proto3" json:"created_at,omitempty"`
	UpdatedAt *timestamppb.Timestamp  `protobuf:"bytes,8,opt,name=updated_at,proto3" json:"updated_at,omitempty"`
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetUsername() *wrapperspb.StringValue {
	if x != nil {
		return x.Username
	}
	return nil
}

func (x *User) GetPassword() *wrapperspb.StringValue {
	if x != nil {
		return x.Password
	}
	return nil
}

func (x *User) GetEmail() *wrapperspb.StringValue {
	if x != nil {
		return x.Email
	}
	return nil
}

func (x *User) GetRoleId() *wrapperspb.StringValue {
	if x != nil {
		return x.RoleId
	}
	return nil
}

func (x *User) GetToken() *wrapperspb.StringValue {
	if x != nil {
		return x.Token
	}
	return nil
}
