// Code generated by protoc-gen-go. DO NOT EDIT.
// This is a stub file. Run `make gen-proto` to regenerate.

package pb

// OrderType enum
type OrderType int32

const (
	OrderType_OrderType_NONE OrderType = 0
	OrderType_ASC            OrderType = 1
	OrderType_DESC           OrderType = 2
)

var OrderType_name = map[int32]string{
	0: "OrderType_NONE",
	1: "ASC",
	2: "DESC",
}

var OrderType_value = map[string]int32{
	"OrderType_NONE": 0,
	"ASC":            1,
	"DESC":           2,
}

func (x OrderType) String() string {
	if name, ok := OrderType_name[int32(x)]; ok {
		return name
	}
	return "OrderType_NONE"
}

// TaskStatus enum
type TaskStatus int32

const (
	TaskStatus_TaskStatus_NONE TaskStatus = 0
	TaskStatus_TaskStatus_TODO TaskStatus = 1
	TaskStatus_IN_PROGRESS     TaskStatus = 2
	TaskStatus_DONE            TaskStatus = 3
)

var TaskStatus_name = map[int32]string{
	0: "TaskStatus_NONE",
	1: "TaskStatus_TODO",
	2: "IN_PROGRESS",
	3: "DONE",
}

var TaskStatus_value = map[string]int32{
	"TaskStatus_NONE": 0,
	"TaskStatus_TODO": 1,
	"IN_PROGRESS":     2,
	"DONE":            3,
}

func (x TaskStatus) String() string {
	if name, ok := TaskStatus_name[int32(x)]; ok {
		return name
	}
	return "TaskStatus_NONE"
}
