// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// This is a stub file. Run `make gen-proto` to regenerate.

package pb

import (
	"context"

	"google.golang.org/grpc"
)

// ─── Task messages ──────────────────────────────────────────────────────────

type Task struct {
	Id          string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title       string     `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description string     `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status      TaskStatus `protobuf:"varint,4,opt,name=status,proto3,enum=pb.TaskStatus" json:"status,omitempty"`
	UserId      string     `protobuf:"bytes,5,opt,name=user_id,proto3" json:"user_id,omitempty"`
	CreatedAt   string     `protobuf:"bytes,6,opt,name=created_at,proto3" json:"created_at,omitempty"`
	UpdatedAt   string     `protobuf:"bytes,7,opt,name=updated_at,proto3" json:"updated_at,omitempty"`
}

type CreateTaskRequest struct {
	Title       string     `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description string     `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Status      TaskStatus `protobuf:"varint,3,opt,name=status,proto3,enum=pb.TaskStatus" json:"status,omitempty"`
	UserId      string     `protobuf:"bytes,4,opt,name=user_id,proto3" json:"user_id,omitempty"`
}

func (x *CreateTaskRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateTaskRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTaskRequest) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TaskStatus_NONE
}

func (x *CreateTaskRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CreateTaskResponse struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

type GetTaskByIDRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetTaskByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTaskByIDResponse struct {
	Data *Task `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

type GetListTaskRequest struct {
	UserId    string    `protobuf:"bytes,1,opt,name=user_id,proto3" json:"user_id,omitempty"`
	Page      int32     `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize  int32     `protobuf:"varint,3,opt,name=page_size,proto3" json:"page_size,omitempty"`
	OrderType OrderType `protobuf:"varint,4,opt,name=order_type,proto3,enum=pb.OrderType" json:"order_type,omitempty"`
	OrderBy   string    `protobuf:"bytes,5,opt,name=order_by,proto3" json:"order_by,omitempty"`
}

func (x *GetListTaskRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetListTaskRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetListTaskRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetListTaskRequest) GetOrderType() OrderType {
	if x != nil {
		return x.OrderType
	}
	return OrderType_OrderType_NONE
}

func (x *GetListTaskRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

type GetListTaskResponse struct {
	Data       []*Task `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Total      int32   `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	TotalPages int32   `protobuf:"varint,3,opt,name=total_pages,proto3" json:"total_pages,omitempty"`
	Page       int32   `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
}

type UpdateTaskRequest struct {
	Id          string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title       string     `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description string     `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status      TaskStatus `protobuf:"varint,4,opt,name=status,proto3,enum=pb.TaskStatus" json:"status,omitempty"`
}

func (x *UpdateTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTaskRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateTaskRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateTaskRequest) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TaskStatus_NONE
}

type UpdateTaskResponse struct{}

type DeleteTaskRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteTaskResponse struct{}

// ─── TaskService interface ──────────────────────────────────────────────────

type TaskServiceServer interface {
	CreateTask(context.Context, *CreateTaskRequest) (*CreateTaskResponse, error)
	GetTaskByID(context.Context, *GetTaskByIDRequest) (*GetTaskByIDResponse, error)
	GetListTask(context.Context, *GetListTaskRequest) (*GetListTaskResponse, error)
	UpdateTask(context.Context, *UpdateTaskRequest) (*UpdateTaskResponse, error)
	DeleteTask(context.Context, *DeleteTaskRequest) (*DeleteTaskResponse, error)
	mustEmbedUnimplementedTaskServiceServer()
}

type UnimplementedTaskServiceServer struct{}

func (UnimplementedTaskServiceServer) CreateTask(context.Context, *CreateTaskRequest) (*CreateTaskResponse, error) {
	return nil, nil
}
func (UnimplementedTaskServiceServer) GetTaskByID(context.Context, *GetTaskByIDRequest) (*GetTaskByIDResponse, error) {
	return nil, nil
}
func (UnimplementedTaskServiceServer) GetListTask(context.Context, *GetListTaskRequest) (*GetListTaskResponse, error) {
	return nil, nil
}
func (UnimplementedTaskServiceServer) UpdateTask(context.Context, *UpdateTaskRequest) (*UpdateTaskResponse, error) {
	return nil, nil
}
func (UnimplementedTaskServiceServer) DeleteTask(context.Context, *DeleteTaskRequest) (*DeleteTaskResponse, error) {
	return nil, nil
}
func (UnimplementedTaskServiceServer) mustEmbedUnimplementedTaskServiceServer() {}

// ─── Registration ───────────────────────────────────────────────────────────

func RegisterTaskServiceServer(s *grpc.Server, srv TaskServiceServer) {}
