// Code generated by protoc-gen-go-grpc / protoc-gen-grpc-gateway. DO NOT EDIT.
// This is a stub file. Run `make gen-proto` to regenerate.

package pb

import (
	"context"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"google.golang.org/grpc"
)

// ─── Request / Response messages ────────────────────────────────────────────

type GetUserByIDRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetUserByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUserByIDResponse struct {
	Data *User `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

type UpdateUserRequest struct {
	Data *User  `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Id   string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *UpdateUserRequest) GetData() *User {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UpdateUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateUserResponse struct{}

type UpdateMeRequest struct {
	Data *User `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

type UpdateMeResponse struct{}

type DeleteUserRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteUserResponse struct{}

type GetListUserRequest struct {
	Page      int32     `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize  int32     `protobuf:"varint,2,opt,name=page_size,proto3" json:"page_size,omitempty"`
	OrderType OrderType `protobuf:"varint,3,opt,name=order_type,proto3,enum=pb.OrderType" json:"order_type,omitempty"`
	OrderBy   string    `protobuf:"bytes,4,opt,name=order_by,proto3" json:"order_by,omitempty"`
}

func (x *GetListUserRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetListUserRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetListUserRequest) GetOrderType() OrderType {
	if x != nil {
		return x.OrderType
	}
	return OrderType_OrderType_NONE
}

func (x *GetListUserRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

type GetListUserResponse struct {
	Data       []*User `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Total      int32   `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	TotalPages int32   `protobuf:"varint,3,opt,name=total_pages,proto3" json:"total_pages,omitempty"`
	Page       int32   `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
}

type Permissions struct {
	Permissions []string `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
}

// ─── UserService interface ──────────────────────────────────────────────────

type UserServiceServer interface {
	GetUserByID(context.Context, *GetUserByIDRequest) (*GetUserByIDResponse, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error)
	UpdateMe(context.Context, *UpdateMeRequest) (*UpdateMeResponse, error)
	DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error)
	GetListUser(context.Context, *GetListUserRequest) (*GetListUserResponse, error)
	mustEmbedUnimplementedUserServiceServer()
}

type UnimplementedUserServiceServer struct{}

func (UnimplementedUserServiceServer) GetUserByID(context.Context, *GetUserByIDRequest) (*GetUserByIDResponse, error) {
	return nil, nil
}
func (UnimplementedUserServiceServer) UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error) {
	return nil, nil
}
func (UnimplementedUserServiceServer) UpdateMe(context.Context, *UpdateMeRequest) (*UpdateMeResponse, error) {
	return nil, nil
}
func (UnimplementedUserServiceServer) DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error) {
	return nil, nil
}
func (UnimplementedUserServiceServer) GetListUser(context.Context, *GetListUserRequest) (*GetListUserResponse, error) {
	return nil, nil
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}

// ─── UserService Client ─────────────────────────────────────────────────────

type UserServiceClient interface {
	GetUserByID(ctx context.Context, in *GetUserByIDRequest, opts ...grpc.CallOption) (*GetUserByIDResponse, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error)
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error)
	GetListUser(ctx context.Context, in *GetListUserRequest, opts ...grpc.CallOption) (*GetListUserResponse, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) GetUserByID(ctx context.Context, in *GetUserByIDRequest, opts ...grpc.CallOption) (*GetUserByIDResponse, error) {
	return nil, nil
}
func (c *userServiceClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error) {
	return nil, nil
}
func (c *userServiceClient) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error) {
	return nil, nil
}
func (c *userServiceClient) GetListUser(ctx context.Context, in *GetListUserRequest, opts ...grpc.CallOption) (*GetListUserResponse, error) {
	return nil, nil
}

// ─── Registration ───────────────────────────────────────────────────────────

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {}

func RegisterUserServiceHandlerClient(ctx context.Context, mux *runtime.ServeMux, client UserServiceClient, opts ...grpc.DialOption) error {
	return nil
}

// ─── API path constants ─────────────────────────────────────────────────────

const (
	UserService_Login_API    = "POST /v1/auth/login"
	UserService_Register_API = "POST /v1/auth/register"
)

var AllPathToMethodMap = map[string]string{
	UserService_Login_API:    "POST /v1/auth/login",
	UserService_Register_API: "POST /v1/auth/register",
}
