// Code generated by protoc-gen-struct-transformer. DO NOT EDIT.
// This is a stub file. Run `make gen-proto` to regenerate.

package transform

import (
	"github.com/glu-project/idl/pb"
	"github.com/glu-project/internal/user/models"
	"github.com/jackc/pgx/v5/pgtype"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

// UserToPbPtr converts a models.User to a pb.User pointer.
func UserToPbPtr(u *models.User) *pb.User {
	if u == nil {
		return nil
	}
	return &pb.User{
		Id:       u.ID,
		Username: wrapperspb.String(u.Username.String),
		Password: wrapperspb.String(u.Password.String),
		Email:    wrapperspb.String(u.Email.String),
		RoleId:   wrapperspb.String(u.RoleID.String),
		Token:    wrapperspb.String(u.Token.String),
	}
}

// UserToPbPtrList converts a slice of models.User pointers to a slice of pb.User pointers.
func UserToPbPtrList(users []*models.User) []*pb.User {
	out := make([]*pb.User, 0, len(users))
	for _, u := range users {
		out = append(out, UserToPbPtr(u))
	}
	return out
}

// PbToUserPtr converts a pb.User to a models.User pointer.
func PbToUserPtr(u *pb.User) *models.User {
	if u == nil {
		return nil
	}
	result := &models.User{
		ID: u.Id,
	}
	if u.Username != nil {
		result.Username = pgtype.Text{String: u.Username.Value, Valid: true}
	}
	if u.Password != nil {
		result.Password = pgtype.Text{String: u.Password.Value, Valid: true}
	}
	if u.Email != nil {
		result.Email = pgtype.Text{String: u.Email.Value, Valid: true}
	}
	if u.RoleId != nil {
		result.RoleID = pgtype.Text{String: u.RoleId.Value, Valid: true}
	}
	if u.Token != nil {
		result.Token = pgtype.Text{String: u.Token.Value, Valid: true}
	}
	return result
}
